name: Swift

on:
  push:
  pull_request:

jobs:
  find-available-devices:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find available devices
        run: xcrun simctl list devices
  build-companion:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: ./hrvm/hrvm_companion_app
        run: swift build
      - name: Test
        working-directory: ./hrvm/hrvm_companion_app
        run: swift test

  build-watch-app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: ./hrvm/hrv_standalone_watch_app
        run: swift build
      - name: Test
        working-directory: ./hrvm/hrv_standalone_watch_app
        run: swift test