# This will build the companion app on IOS devices and the watch app on watchOS devices.
name: xcode build

on:
  push:
  pull_request:

jobs: 
  build-companion-xcode:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: ./hrvm/hrvm_companion_app/
        run: xcodebuild clean build analyze -scheme "HRVMonitor WatchKit App" -destination 'platform=iOS Simulator, id=004DCB5F-255C-4ECE-9C55-651D4312C607, OS=16.2, name=iPhone 14'
  build-watch-app-xcode:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: ./hrvm/hrv_standalone_watch_app
        run: xcodebuild build -scheme "HRVMonitor WatchKit App" -destination 'platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm,OS=8.0'